language: java
deploy:
  provider: releases
  api_key:
    secure: mSmnTOrlBe0BWcnDBY/CWGT4iWw0CYau1eFpNRFY5qdG2VZVCIS+OvF6PnlXA4JMKyQeKXVDpn8zVnL6JIIZtt/Bea6X1JC1s4GUJp2Iazkz0P9myiIGM2g/JSrgtsi/WmlvXq8PY506CtDrIpGFnwaYlf8qg+/xaxnia2+jWAnWJlrBPW8FoQd11MT4A5g3I5NX7T6Fy/IJZFw8zU97FiQJxJAx//qG2RKkpY0jHo26P+Ec5cj5ghgpesa869bYl4P0QL+AsTnORXjTOPgvkQIc6cOd0Bt9gumALg3JiRrwW6N91w0AKy0BgCrte1/AUsRny4r5wUO9TVxoxcmNK/zsKxPIezVZRnKSNcpv7Wmw/kq9UWWdwxPemsj9oDq/HtcPetweVucxgfp5L2Gsex2VoT01slDLpbhYonny+AOlDY4WRAZPhfT8zei5A/T6FkLzHtkQncqQ8kx6MahZJp8WYMBKIDT3EWelqY7plwuQmixgwgFgZDZFLdavcXUfMtTq4i9itfQ/0D1Ugd/5HYlT5Pk56ULqyubXSimCYsYALy8yQUb/yeDVU+7QGwvT1Y/SHe+0lyI2+019rSu9BNRXBifQ3ZkVOw/mPNpSTghdnlngc29K4xdmMUij4vVCOQu1jiSEfyEUNL+sTH+h5EBm/0TuBrWWCFFEFL8Facg=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-overthere-smb-converter-plugin
notifications:
  slack:
    secure: k5+dLaF5b4OsNIZRb5EqJ5OArvCUhdrBG7ugpzcwKq+gdqjekpWUarXThzHJQRtGN9WYGU9pl+ntpkQtQf24mg7zxo2NMadan62yxedgBj9YFCp/U1hz3KIqGsQnkml+OtfJjfD+xfqEaSfJFP86TbL/knpgBmjrcQtA4Xo6QpOEa1DM69NO90JfCphPgyhhpb8ze4K7ADnKczQZBKWvv29A2jzZycYQz4v1CQ4Pzz2GCrZanpQbmcEK/ZGgBIva75ownmWXicdFuih4RnyM7gkIFbvCj6HrmJqU+McCd2s/ECcS/H7tTai6MoMZ1WHLPElApErMVjYQ5M3sxWToKNawtQqu1n+S/3De8+C+L6sdOafnoBXcd+dPBJa78ZWhCoZ1n9+ZMT+/s7IsM6wIesW7IMMWAH6httPXgGyCR73/3DAuWjMFR6RbIUmCSwJVtePE3eBsVwdy3E3SZkBay5lirGvKcLPCQ+MNLQg67jWgSfrq93c34aK4+kTTSoi9RO7eU0sOgHIsEDrZ6oQM4cZC/JXRRYnkS5Xy/TMMB3oDmO56MrW8JM1FmwdtnGJIIjjiktTt+jar7KX8Byhsut41J1VpEccyuB2JUwkfFRFO7x/VD72CSlIqAeVaJnAQ7CWRMi5V7i1cNOMBtg66K7sazsqlm4qEwxzskoHiJu8=
