language: java
deploy:
  provider: releases
  api_key:
    secure: UVKwAlXYBST77XlRcbH57adPcb6U/rqUhe6YeWiaQA5lAcqzf7ZYA929wLFoZFYMNS5CoIDaLxLrn09q7DR5WsaHmIZuPLcnKf6EmkUl95HHsPJ8uq0Tbdlq1uugy1BVGGaRTfU24Tw42vLnFolrfWxSvCyyekkDiUIMdeghpcTtrWBsOF4hMazRU7midfi8u41gl+ruj2buWIFWPkoM+YUaq658RT6aCRplY3u4I8sjgBf+FnVKvJHXV15G5f3b2O6hVU0WDknUMW7hxPwwgqSWHxyDhxH/1PVgqUsx8RViXEpDbAmiz7NFScavcY7Bj3YRf1CmIW2qbu8nosqGqppRlIxOdYygXdnrqERHvQ+wULiOWIADpfxjh+D0Un82X5FGf6C/vwF8uL9tFrkqq8cfIib9PXG5XFUUBoTOkZaLiJTMI6ZNjNsMJtB/pvXzcLpTEznMWsdhHeVFkq/enD7pw25E5J797Z/5oEBZQ9Ka17Oz/0JQv1rgKKsk9ykIaTbMDx/czZL7msv0MJk13OB8yZP3AJSHuf+Wgmnx0xOn0UF7EKYa3eHigDrzZ+LgKKj6M7xnJskLWxBVUa+sDOl0mDqjXdB5BxOiQCmvTfWO/OkrUQWnxYZXy59rUeWQ9YZ0agQyRZ34xJiLdOsLz/nPC1nGYVRIlysQ42dlsms=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-overthere-smb-converter-plugin
notifications:
  hipchat:
    rooms:
      secure: Ms9HNIwZjunIJPhJQgA7BjrcH0IC443mWiQ368vA6184DHplyQxSqJbpHPMcVF/9K6Sf0zn/hFktdHptPp/vxUaq/7/N1HJG9/Yx2M6XXki0lS83g6jtP4JewHtwwVATqKxaQ8UDQwiyBkgZq/T0HZMLOYcVeX1/e9/zVqQ4h1nDMR17mdg6tfllBoE7vL6/GJbMvw2ExBqV38TvcsQfIiBsZ3Lz3wgQuzPk1T7+66TUKjN0ODtS+Lx04Uzy1upPbmV/KVE7a3Wl0H/S/u+qGWnkD9OsBQC/bIoViudx5xutVsDO4cPtvkCW6Ot386kRzXdTd8CPhn3OGgiC37GyFDYZbDUYtdnf7vniacMmwWBuZEHf/X8ee9VT+Ps5Nu3rM1UE09GdqBKxsRLFr0ectxQmluNQ6tirEhTB+k5CXDia1k1SdC5+RH8KQq1xCtmizcUdOI9LVuifA2rK6PRhwzle35L+NBs2YeHA5M0Yn/vYb6ZCO98stcSCRyviwXCGyxRklwxMUYapE/+9Ws4PUkESUr/H+CTUihIQOCRIrNZbxdesq4J5xHWrhhm3+mWWmCUs/bGV0rGYEUkATqL0nBes2eBVm0sNyPHhQfX1MA8bJQpZCnBxkziE2PO+MH1HKtx3vyxvOZFhzUFORyrkip812/kFjsDBck4Nczd4oZ4=
