language: java
deploy:
  provider: releases
  api_key:
    secure: mSmnTOrlBe0BWcnDBY/CWGT4iWw0CYau1eFpNRFY5qdG2VZVCIS+OvF6PnlXA4JMKyQeKXVDpn8zVnL6JIIZtt/Bea6X1JC1s4GUJp2Iazkz0P9myiIGM2g/JSrgtsi/WmlvXq8PY506CtDrIpGFnwaYlf8qg+/xaxnia2+jWAnWJlrBPW8FoQd11MT4A5g3I5NX7T6Fy/IJZFw8zU97FiQJxJAx//qG2RKkpY0jHo26P+Ec5cj5ghgpesa869bYl4P0QL+AsTnORXjTOPgvkQIc6cOd0Bt9gumALg3JiRrwW6N91w0AKy0BgCrte1/AUsRny4r5wUO9TVxoxcmNK/zsKxPIezVZRnKSNcpv7Wmw/kq9UWWdwxPemsj9oDq/HtcPetweVucxgfp5L2Gsex2VoT01slDLpbhYonny+AOlDY4WRAZPhfT8zei5A/T6FkLzHtkQncqQ8kx6MahZJp8WYMBKIDT3EWelqY7plwuQmixgwgFgZDZFLdavcXUfMtTq4i9itfQ/0D1Ugd/5HYlT5Pk56ULqyubXSimCYsYALy8yQUb/yeDVU+7QGwvT1Y/SHe+0lyI2+019rSu9BNRXBifQ3ZkVOw/mPNpSTghdnlngc29K4xdmMUij4vVCOQu1jiSEfyEUNL+sTH+h5EBm/0TuBrWWCFFEFL8Facg=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-overthere-smb-converter-plugin
notifications:
  hipchat:
    rooms:
      secure: Ms9HNIwZjunIJPhJQgA7BjrcH0IC443mWiQ368vA6184DHplyQxSqJbpHPMcVF/9K6Sf0zn/hFktdHptPp/vxUaq/7/N1HJG9/Yx2M6XXki0lS83g6jtP4JewHtwwVATqKxaQ8UDQwiyBkgZq/T0HZMLOYcVeX1/e9/zVqQ4h1nDMR17mdg6tfllBoE7vL6/GJbMvw2ExBqV38TvcsQfIiBsZ3Lz3wgQuzPk1T7+66TUKjN0ODtS+Lx04Uzy1upPbmV/KVE7a3Wl0H/S/u+qGWnkD9OsBQC/bIoViudx5xutVsDO4cPtvkCW6Ot386kRzXdTd8CPhn3OGgiC37GyFDYZbDUYtdnf7vniacMmwWBuZEHf/X8ee9VT+Ps5Nu3rM1UE09GdqBKxsRLFr0ectxQmluNQ6tirEhTB+k5CXDia1k1SdC5+RH8KQq1xCtmizcUdOI9LVuifA2rK6PRhwzle35L+NBs2YeHA5M0Yn/vYb6ZCO98stcSCRyviwXCGyxRklwxMUYapE/+9Ws4PUkESUr/H+CTUihIQOCRIrNZbxdesq4J5xHWrhhm3+mWWmCUs/bGV0rGYEUkATqL0nBes2eBVm0sNyPHhQfX1MA8bJQpZCnBxkziE2PO+MH1HKtx3vyxvOZFhzUFORyrkip812/kFjsDBck4Nczd4oZ4=
